i_en = [
'Go for a walk in the park',
'Start reading a new book',
'Try to cook a new dish',
'Sign up for a drawing course',
"Watch a movie I've wanted for a long time",
'Do a general cleaning of the house',
'Call an old friend',
'Start keeping a gratitude diary',
'Plant flowers on the balcony',
'Do exercises in the morning',
'Go for a bike ride',
'Learn a new foreign language',
'Visit a museum or exhibition',
'Play a board game with your family',
'Write a letter to a pen pal',
'Go for a run in the morning',
'Do a photo shoot in nature',
'Listen to new music or podcast',
'Plan your dream trip',
'Upgrade your wardrobe or shop online',
'Spend a day without gadgets and social media',
'Try meditation or yoga',
'Create your own cocktail or dessert recipe',
'Learn a new skill through an online course',
'Visit a zoo or aquarium',
'Play a video game or a computer simulator',
'Spend the evening painting or needlework',
'Organize a picnic in nature',
'Gardening or taking care of plants at home',
'Write a short story or a poem',
'Arrange a home spa day with masks and massage',
'Watch an old movie or TV series from my childhood',
'Upgrade your home interior with DIY projects',
'Go to a cooking or needlework workshop',
'Do volunteer work online or offline',
'Create a playlist of your favorite songs and listen to it all day long',
'Try new sports (for example, rock climbing, badminton)',
'Organize a photo shoot with friends or family outdoors',
'Plan your next trip or dream vacation ',
'Learn to play a musical instrument (guitar, piano)',
', engage in culinary experiments — for example, bake something unusual ',
'Read an article or book on personality development ',
'Create a collage of photos and memories ',
'Spend a day without plans — just relax and enjoy the moment ',
'Update your blog or social media with new ideas ',
'Do yoga or pilates at home ',
"Visit the farmer's market and buy fresh produce",
'Try new types of tea or coffee ',
'Plan a day for self—development - learning new skills, languages, etc.',
'Create a list of goals for the year ahead ',
'Create a cozy place to read at home ',
'Do needlework — knitting, embroidery, jewelry making ',
'Stroll through a new area of the city and discover new places ',
'Arrange an evening of board games with friends ',
'Upgrade your library of e-books and audiobooks ',
'Watch a documentary about nature, space, or history  ',
'Write thank-you letters to loved ones  ',
'Organize a mini-experiment to improve habits  ',
'Create your own garden on the windowsill  ',
'Try new healthy food recipes  ',
'Start planning your budget and financial future  ',
'Learn new drawing or painting techniques  ',
'Go on a guided city tour  ',
'Arrange a day without electricity — disconnect from gadgets and enjoy nature ', 
'Sign up for a dance course online or offline  ',
'Create a video blog about your hobbies  ',
'Meet new people through themed events online/offline  ',
'Upgrade your programming/design/photography skills  ',
'Spend the day in silence and meditation to restore energy  ',
'Make a list of books you want to read in a year  ',
'Organize a home theater with popcorn and your favorite movies  ',
'Start keeping a diary of successes and achievements  ',
'Start planning your garden or vegetable garden  ',
'Take part in a charity event or fundraiser',
'Attend a ceramics or pottery workshop',
'Make a homemade scrub or face mask',
'Listen to a podcast on a topic of interest',
'Spend the day exploring a new culture through movies, music, and food',
'Create your own comic book or illustrated story',
'Try to make homemade yogurt or kvass',
'Arrange a retro or themed photo shoot',
"Visit the farmer's market and try new products",
'Make DIY gifts for loved ones on a holiday or just like that',
'Spend an evening studying astronomy — stargazing',
'Create a meal plan for a week or a month',
'Try new types of needlework, such as decoupage or scrapbooking.',
'Attend a dance workshop (salsa, ballroom dancing)',
'Make a map of desires and goals for the future',
'Spend the day disconnected from all notifications and social media',
'Learn meditation techniques using apps or video tutorials',
'View old family videos and photo albums',
'Try to make your own homemade cheese or yogurt',
'Organize a themed party at home (for example, a movie night or an evening of Italian cuisine)',
'Start keeping a video diary about your hobbies and life',
'Visit a local craft fair and buy unique items',
'Make a collage of your goals and dreams on the wall',
'Try new types of fitness — for example, Pilates or tai bo',
'Spend the day exploring the history of your city through guided tours and museums',
'Create your own fragrance — perfume or candles with aromatic oils',
'Play a quest room with friends or family (online or offline)',
'Start blogging about your travels and experiences',
'Make homemade bread or pastries according to a new recipe',
'Visit the local zoo or botanical garden at other times of the year for new experiences.',
'Learn the technique of calligraphy or handwriting',
'Spend the day doing good deeds for others — volunteering, helping neighbors',
'Create your own collection of postcards or stamps (if interested)',
'Try new outdoor sports, such as kitesurfing, skateboarding',
'Arrange an evening of board games with friends online via video link',
'Make your own jewelry from polymer clay or beads',
'Watch a documentary series about nature, technology, or history',
'Start keeping a dream diary — write down your desires and ideas',
'Try to make homemade candies or chocolate truffles',
'Arrange a photo shoot with pets (if available)',
'Attend a candle or soap making workshop',
'Create your own video about your favorite hobby',
'Go for a walk to find interesting architectural details in the city',
'Learn new photography techniques, such as macro photography or night photography.',
'Spend a day without shopping — focus on using existing items',
'Make a selection of books/films on a specific topic for future viewing/reading',
'Try to make your own homemade lemonade or juice from fresh fruits',
'Arrange an evening of nostalgia: watch old movies, listen to music from previous years',
'Start keeping a diary of goals and progress towards achieving them',
'Visit the local library and choose new books to read',
'Make a mini vegetable garden on the windowsill from herbs and vegetables',
'Try new breathing techniques for relaxation and stress relief',
'Organize viewing of old photos with friends online and recall funny moments',
'Create your own calendar of events for next year with important dates and plans',
'Play online games with friends for fun and socializing']